import React, { useEffect, useMemo, useState } from 'react';
import { Alert, Pressable, Share, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { createInviteCode, roleLabel } from './sharing';
import { CalendarItem, CalendarMember, MemberRole, loadMembers, saveMembers } from './storage';
const BRAND='#5B4CF0'; const ROLE_OPTIONS:MemberRole[]=['editor','viewer'];
const defaultMembers=(calendarId:string):CalendarMember[]=>[{id:'me',calendarId,name:'星火使用者',role:'owner',avatarText:'火'}];
export default function SharedMembersPanel({calendar}:{calendar:CalendarItem}){
 const [members,setMembers]=useState<CalendarMember[]>([]),[name,setName]=useState(''),[role,setRole]=useState<MemberRole>('editor'),[inviteCode,setInviteCode]=useState(calendar.inviteCode||createInviteCode()),[ready,setReady]=useState(false);
 useEffect(()=>{loadMembers(defaultMembers(calendar.id)).then(all=>{const own=all.filter(m=>m.calendarId===calendar.id);setMembers(own.length?own:defaultMembers(calendar.id));setReady(true);});},[calendar.id]);
 useEffect(()=>{if(!ready)return;loadMembers([]).then(all=>saveMembers([...all.filter(m=>m.calendarId!==calendar.id),...members]).catch(()=>undefined));},[members,ready,calendar.id]);
 const canManage=useMemo(()=>members.some(m=>m.id==='me'&&m.role==='owner'),[members]);
 const addMember=()=>{const n=name.trim();if(!n)return Alert.alert('請輸入成員名稱');setMembers(v=>[...v,{id:`member-${Date.now()}`,calendarId:calendar.id,name:n,role,avatarText:n.slice(0,1)}]);setName('');};
 const removeMember=(id:string)=>{const t=members.find(m=>m.id===id);if(!t||t.role==='owner')return;Alert.alert('移除成員',`確定要移除「${t.name}」嗎？`,[{text:'取消',style:'cancel'},{text:'移除',style:'destructive',onPress:()=>setMembers(v=>v.filter(m=>m.id!==id))}]);};
 const shareInvite=async()=>{try{await Share.share({title:`加入 ${calendar.name}`,message:`邀請你加入 WDTD 星火日曆「${calendar.name}」\n邀請碼：${inviteCode}\n\n打開星火日曆並輸入邀請碼即可加入。`});}catch{Alert.alert('分享失敗','目前無法開啟系統分享功能。');}};
 const regenerate=()=>Alert.alert('重新產生邀請碼','舊邀請碼之後將無法使用。確定要更新嗎？',[{text:'取消',style:'cancel'},{text:'更新',onPress:()=>setInviteCode(createInviteCode())}]);
 if(!calendar.shared)return null;
 return <View style={s.wrapper}><Text style={s.section}>共享與成員</Text><View style={s.invite}><View style={{flex:1}}><Text style={s.label}>邀請碼</Text><Text style={s.code}>{inviteCode}</Text><Text style={s.meta}>分享邀請碼給朋友，之後可加入這個共享日曆。</Text></View><Pressable style={s.refresh} onPress={regenerate}><Ionicons name="refresh" size={20} color={BRAND}/></Pressable></View><Pressable style={s.share} onPress={shareInvite}><Ionicons name="share-social-outline" size={20} color="#fff"/><Text style={s.shareText}>分享邀請</Text></Pressable><View style={s.list}>{members.map(m=><View key={m.id} style={s.row}><View style={s.avatar}><Text style={s.avatarText}>{m.avatarText||m.name.slice(0,1)}</Text></View><View style={{flex:1}}><Text style={s.name}>{m.name}{m.id==='me'?'（你）':''}</Text><Text style={s.meta}>{roleLabel(m.role)}</Text></View>{m.role!=='owner'&&canManage&&<View style={s.actions}><Pressable style={s.roleButton} onPress={()=>setMembers(v=>v.map(x=>x.id===m.id?{...x,role:x.role==='editor'?'viewer':'editor'}:x))}><Text style={s.roleText}>{m.role==='editor'?'改僅查看':'改可編輯'}</Text></Pressable><Pressable style={s.remove} onPress={()=>removeMember(m.id)}><Ionicons name="close" size={18} color="#D94B58"/></Pressable></View>}</View>)}</View>{canManage&&<View style={s.addBox}><TextInput value={name} onChangeText={setName} placeholder="成員名稱" style={s.input}/><View style={s.roles}>{ROLE_OPTIONS.map(o=><Pressable key={o} onPress={()=>setRole(o)} style={[s.roleChip,role===o&&s.roleActive]}><Text style={[s.roleChipText,role===o&&{color:BRAND}]}>{roleLabel(o)}</Text></Pressable>)}</View><Pressable style={s.add} onPress={addMember}><Ionicons name="person-add-outline" size={20} color="#fff"/><Text style={s.shareText}>加入測試成員</Text></Pressable></View>}</View>;
}
const s=StyleSheet.create({wrapper:{gap:10,marginTop:4},section:{fontSize:13,fontWeight:'800',color:'#8C8E95'},invite:{padding:14,borderRadius:16,backgroundColor:'#F4F2FF',flexDirection:'row',alignItems:'center',gap:12},label:{fontSize:12,color:'#777',fontWeight:'700'},code:{fontSize:26,fontWeight:'900',letterSpacing:3,color:BRAND,marginVertical:4},meta:{fontSize:12,color:'#92949B',lineHeight:17},refresh:{width:42,height:42,borderRadius:14,backgroundColor:'#fff',alignItems:'center',justifyContent:'center'},share:{height:48,borderRadius:14,backgroundColor:BRAND,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},shareText:{color:'#fff',fontWeight:'800'},list:{borderRadius:16,backgroundColor:'#fff',borderWidth:1,borderColor:'#ECECF0',overflow:'hidden'},row:{minHeight:68,padding:12,flexDirection:'row',alignItems:'center',gap:10,borderBottomWidth:1,borderBottomColor:'#F1F1F3'},avatar:{width:40,height:40,borderRadius:20,backgroundColor:BRAND,alignItems:'center',justifyContent:'center'},avatarText:{color:'#fff',fontWeight:'800'},name:{fontSize:15,fontWeight:'800'},actions:{flexDirection:'row',alignItems:'center',gap:6},roleButton:{padding:8,borderRadius:9,backgroundColor:'#F1EFFF'},roleText:{fontSize:11,fontWeight:'800',color:BRAND},remove:{width:30,height:30,borderRadius:10,backgroundColor:'#FFF0F1',alignItems:'center',justifyContent:'center'},addBox:{padding:12,borderRadius:16,backgroundColor:'#fff',borderWidth:1,borderColor:'#ECECF0',gap:9},input:{height:44,borderRadius:12,backgroundColor:'#F7F7F9',paddingHorizontal:12,fontSize:15},roles:{flexDirection:'row',gap:8},roleChip:{paddingHorizontal:12,paddingVertical:8,borderRadius:10,borderWidth:1,borderColor:'#E5E5E8'},roleActive:{backgroundColor:'#F1EFFF',borderColor:BRAND},roleChipText:{fontSize:12,fontWeight:'700',color:'#666'},add:{height:44,borderRadius:12,backgroundColor:BRAND,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7}});
